### ISSUE TITLE
Possibly a bug in line 200 of hyper.py

### ISSUE THREAD

**Issue by panzhang83** [jcmgray/cotengra#1]
For example, if methods="greedy", after the following line,
`self._methods = DEFAULT_METHODS if methods is None else list(methods) `
self._methods would become ['g','r','e','e','d','y'] which is not expected.
I think line 200 should be modified as
`self._methods = DEFAULT_METHODS if methods is None else [methods]`

**Comment by jcmgray** [comment]
So the `methods` parameter is intentionally meant to be an iterable of str
```python
"""
Parameters
    ----------
    methods : None or sequence[str], optional
        Which methods to use from ``list_hyper_functions()``.
"""
```
so you would need to supply `methods=['greedy']`, though it might be convenient to specially handle the case of a string supplied as a single method!

**Comment by jcmgray** [comment]
As of [this commit](https://github.com/jcmgray/cotengra/commit/751bf8373f2e483931106f5e252c24d0878ca88c) you can supply single strings!
