### ISSUE TITLE
Optuna depreciation warnings: `suggest_loguniform`

### ISSUE THREAD

**Issue by lm1909** [jcmgray/cotengra#16]
Optuna seems to have [deprecated a couple of features in v3.0.0](https://github.com/optuna/optuna/releases/tag/v3.0.0#Enhancements:~:text=for%20more%20details.-,Breaking%20Changes,-Changes%20to%20the), which results in warnings like
```.../cotengra/hyper_optuna.py:21: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.``` caused by this:
https://github.com/jcmgray/cotengra/blob/718b0bd3a9c80bdac74ddeb922055c5bcf1a5b71/cotengra/hyper_optuna.py#L21

**Comment by alex-orca** [comment]
I am also getting the above warning accompanied another one for the deprecation of suggest_uniform :
`cotengra/hyper_optuna.py:18: FutureWarning: suggest_uniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :func:`~optuna.trial.Trial.suggest_float` instead.`

**Comment by jcmgray** [comment]
Thanks for the issue, looks like it's simply a matter of changing `suggest_float(log={False|True})` instead (which I presume has been available for a number of version). I should get to it soon, unless anyone wants to submit a PR first!

**Comment by jcmgray** [comment]
This should be fixed by https://github.com/jcmgray/cotengra/commit/2d8b6b406b34fe63c91362e46966dd589d9cddad.
