### ISSUE TITLE
optimize='hyper-spinglass'

### ISSUE THREAD

**Issue by panzhang83** [jcmgray/cotengra#2]
In the following code:
`eq, shapes = oe.helpers.rand_equation(100, 3,d_min=2,d_max=2,seed=1)
path, info = oe.contract_path(eq, *shapes, shapes=True, optimize='hyper-spinglass')
`
I encountered "KeyError: "Path optimizer 'auto-hq' not found, valid options are {'random-greedy', 'quickbb-2', 'flowcutter-60', 'branch-all', 'hyper-greedy', 'hyper-256', 'quickbb-10', 'flowcutter-10', 'hyper-betweenness', 'flowcutter-2', 'eager', 'greedy', 'auto', 'branch-1', 'dynamic-programming', 'quickbb-60', 'hyper', 'hyper-kahypar', 'branch-2', 'hyper-spinglass', 'dp', 'opportunistic', 'optimal'}.""

It seems that somehow in the core.py: ContractionTree.contract(), the optimize is still the default value 'auto-hq', instead of spinglass.

**Comment by jcmgray** [comment]
You will need to install a develop version of opt_einsum. 'auto-hq' is the optimizer used to combine partitions when there are more than 2.
________________________________

**Comment by jcmgray** [comment]
Let me know if that gets it working!

**Comment by panzhang83** [comment]
I have installed opt_einsum 3.1.0, can you explain in detail how to install the develop version?

By the way, code `path, info = oe.contract_path(eq, *shapes, shapes=True, optimize='hyper-kahypar')` also outputs "KeyError: "Path optimizer 'auto-hq' not found,...", together with many lines of "No filename for partition file specified"

**Comment by jcmgray** [comment]
Hi sorry by 'develop' version I meant the latest (currently unreleased) version on github. You can either clone it to you computer and install it locally:
```bash
$ git clone https://github.com/dgasmith/opt_einsum.git
$ pip install -U -e opt_einsum/
```
The `-U` means update and the `-e` means editable - you can make changes and pull commits and when you reimport `opt_einsum` the changes will immediately come into effect.

Or you install directly from the github repo:
```bash
$ pip install -U git+https://github.com/dgasmith/opt_einsum.git
```

**Comment by panzhang83** [comment]
Yes, installing the develop version of opt_einsum solved my problem. Thanks!
