### ISSUE TITLE
Create a tag or a release

### ISSUE THREAD

**Issue by MoiseRousseau** [jcmgray/cotengra#22]
Hi!

I am Moise Rousseau, a HPC analyst at Calcul Quebec. I would like to deploy a pre-compiled wheel of Cotengra optimized for our systems for some of our users. However, our policy requires a official release on PyPi / GitHub or at least, a tag on GitHub.

Can you create such a tag or release ? You can do so with the link "Create a new release" on the right of the repository page.

Regards,
Moise

**Comment by jcmgray** [comment]
Hi @MoiseRousseau, I've tagged and released `v0.2.0` on `pypi`. Going forward I'll automate the process and hopefully upload `cotengra` to `conda-forge` too.

**Comment by jcmgray** [comment]
Closing for now, feel free to reopen and let me know if you have any issues
