### ISSUE TITLE
way to convert ContractionTree to PathInfo?

### ISSUE THREAD

**Issue by xywu1990** [jcmgray/cotengra#8]
hi, I didn't manage to find a convinient way to do this. is there?

**Comment by jcmgray** [comment]
Hi @xywu1990 - sorry to be slow over the holidays - the simplest way to do this is just to use the ``.path()`` from the tree:
```python
info = oe.contract_path(eq, *arrays, optimize=tree.path())
```
also note much of the information in the path info object is already available from the contraction tree - e.g. ``tree.max_size()`` etc. 

Also note that the ``ContractionTree`` is not *strictly* the same information as the ``PathInfo`` object - which is a specific ordering of the contraction tree.

**Comment by xywu1990** [comment]
Thanks. @jcmgray
